//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL.CatalogoProdServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CatalogoProdServiceReference.ICatalogoProdService")]
    public interface ICatalogoProdService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoProdService/GetAll", ReplyAction="http://tempuri.org/ICatalogoProdService/GetAllResponse")]
        ML.CatalogoProducto[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoProdService/GetAll", ReplyAction="http://tempuri.org/ICatalogoProdService/GetAllResponse")]
        System.Threading.Tasks.Task<ML.CatalogoProducto[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoProdService/Add", ReplyAction="http://tempuri.org/ICatalogoProdService/AddResponse")]
        bool Add(string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoProdService/Add", ReplyAction="http://tempuri.org/ICatalogoProdService/AddResponse")]
        System.Threading.Tasks.Task<bool> AddAsync(string descripcion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICatalogoProdServiceChannel : PL.CatalogoProdServiceReference.ICatalogoProdService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CatalogoProdServiceClient : System.ServiceModel.ClientBase<PL.CatalogoProdServiceReference.ICatalogoProdService>, PL.CatalogoProdServiceReference.ICatalogoProdService {
        
        public CatalogoProdServiceClient() {
        }
        
        public CatalogoProdServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CatalogoProdServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogoProdServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogoProdServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ML.CatalogoProducto[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<ML.CatalogoProducto[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public bool Add(string descripcion) {
            return base.Channel.Add(descripcion);
        }
        
        public System.Threading.Tasks.Task<bool> AddAsync(string descripcion) {
            return base.Channel.AddAsync(descripcion);
        }
    }
}
